version: "3"
services:
  redis:
    image: redis
    networks:
      - webnet
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
  postgres:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: volunteer_api
  api:
    image: api:v1
    ports: 
      - "3000:3000"
    networks:
      - webnet
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_USER: postgres    
      DB_PASSWORD: postgres
      DB_NAME: volunteer_api
      REDIS_HOST: redis
    command: ["./wait-for-it.sh", "postgres:5432", "redis:6379", "--", "yarn", "start"]
networks:
  webnet: